#!/bin/sh

# sudo not required for some system commands
for command in mount umount sv pacman updatedb su shutdown poweroff reboot ; do
	alias $command="sudo $command"
done; unset command

alias \
	cp="cp -iv" \
	mv="mv -iv" \
	rm="rm -vI" \
	bc="bc -ql" \
	rsync="rsync -vrPlu" \
	mkd="mkdir -pv" \
  mkdir="mkdir -p"
	yt="yt-dlp --embed-metadata -i" \
	yta="yt -x -f bestaudio/best" \
	ytt="yt --skip-download --write-thumbnail" \
	ffmpeg="ffmpeg -hide_banner"

alias \
	ls="ls -hN --color=auto --group-directories-first" \
	grep="grep --color=auto" \
	diff="diff --color=auto" \
	ccat="highlight --out-format=ansi" \
	ip="ip -color=auto"

alias \
	ka="killall" \
	# g="git" \
	v="$EDITOR" \
	z="zathura"


# Handy change dir shortcuts
alias \
  ..='cd ..' \
  ...='cd ../..' \
  .3='cd ../../..' \
  .4='cd ../../../..'  \
  .5='cd ../../../../..'

# Helpful aliases
alias \
  l='eza -lh  --icons=auto' \
  ls='eza -1   --icons=auto' \
  ll='eza -lha --icons=auto --sort=name --group-directories-first' \
  ld='eza -lhD --icons=auto' \
  un='$aurhelper -Rns' \
  up='$aurhelper -Syu' \
  pl='$aurhelper -Qs' \
  pa='$aurhelper -Ss' \
  pc='$aurhelper -Sc' \
  po='$aurhelper -Qtdq | $aurhelper -Rns -' \
  vc='code --ozone-platform-hint=wayland --disable-gpu' \
  sail='./vendor/bin/sail' \

# Fixes "Error opening terminal: xterm-kitty" when using the default kitty term to open some programs through ssh
alias ssh='kitten ssh'
alias dots=~/scripts/dotfiles.sh
